academy/urls.py
from django.urls import path, include
from django.contrib import admin
from django.views.generic import TemplateView
from rest_framework.documentation import include_docs_urls
from rest_framework import permissions

urlpatterns = [

    path('', TemplateView.as_view(template_name="main/index.html")),
    path('docs/', include_docs_urls(title='JSA API', public=False, permission_classes=(permissions.IsAdminUser,))),
    path('terms/', TemplateView.as_view(template_name="main/terms_of_service.html")),
    path('upgrade-now/', TemplateView.as_view(template_name="main/upgrade_now.html")),
    path('fat-loss-init/', TemplateView.as_view(template_name="main/fat_loss_landing.html")),
    path('transformations/', TemplateView.as_view(template_name="main/transformations.html")),
    path('member-of-the-month/', TemplateView.as_view(template_name="main/member_of_the_month.html")),
    path('privacy/', TemplateView.as_view(template_name="main/privacypolicy.html")),
    path('cookies-policy/', TemplateView.as_view(template_name="main/cookies_policy.html")),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('emails/', include(('emails.urls', 'emails'), namespace='emails')),
    path('transactions/', include(('transactions.urls', 'transactions'), namespace='transactions')),
    path('weeks/', include(('weeks.urls', 'weeks'), namespace='weeks')),
    path('chat/', include(('chat.urls', 'chat'), namespace='chat')),
    path('modules/', include(('modules.urls', 'modules'), namespace='modules')),
    path('progress/', include(('progress.urls', 'progress'), namespace='progress')),
    path('recipes/', include(('recipes.urls', 'recipes'), namespace='recipes')),
    path('training/', include(('training.urls', 'training'), namespace='training')),
    path('accounts/', include('registration.backends.default.urls')),
    path('oauth/', include(('social_django.urls', 'social_django'), namespace='social')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('coaches/', include(('coaches.urls', 'coaches'), namespace='coaches')),
    path('challenge/', include(('challenge.urls', 'challenge'), namespace='challenge')),
    path('analytics/', include(('analytics.urls', 'analytics'), namespace='analytics')),
    path('nutrition-tracker/', include(('nutrition_tracker.urls', 'nutrition'), namespace='nutrition_tracker')),
    path('foods/', include(('foods.urls', 'foods'), namespace='foods')),
    path('home-steps/', include(('home_steps.urls', 'home_steps'), namespace='home_steps')),
    path('jsa-admin-coach-login/', admin.site.urls),

]

blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^view/(?P<slug>[^\.]+).html', views.view_post, name='view_blog_post'),
	url(r'^category/(?P<slug>[^\.]+).html', views.view_category, name='view_blog_category'),
]

users/urls.py
from django.urls import path
from . import views
from .backends import Register
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='home'),
    path('account/', views.account, name='account'),
    path('membership-options/', views.membership_options, name='membership_options'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('gift-coupon/', views.gift_coupon, name='gift_coupon'),
    path('coach-profile/', views.coach_profile, name='coach_profile'),
    path('one-time-offers/', views.one_time_offers, name='one_time_offers'),
    path('profile/picture/', views.profile_pic, name='profile_pic'),
    path('save-fb-picture/', views.save_fb_picture, name='save_fb_picture'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('register/', Register.as_view(), name='user_register'),
    path('social/settings/password', views.social_settings_password, name='social_settings_password'),
    path('update-details/', views.update_user_details, name='update_user_details'),
    path('set-first-name/', views.set_first_name, name='set_first_name'),
    path('csv-export/', views.export_users_csv, name='export_users_csv'),
    path('export-users-canceled/', views.export_users_canceled, name='export_users_canceled'),
    path('export-users-last-challenge/', views.export_users_last_challenge, name='export_users_last_challenge'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from pyuploadcare.dj.models import ImageField


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE, db_index=True)
    image = ImageField(null=True)

    def __str__(self):
    	return self.user.username


class CoachProfile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE, db_index=True)
    image = ImageField(null=True)

    def __str__(self):
    	return self.user.username

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.utils.html import strip_tags
from django.contrib.auth.decorators import login_required
from social_django.models import UserSocialAuth
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from .models import Profile, CoachProfile
from django.contrib.auth.models import User
from django.contrib.auth.decorators import user_passes_test
from transactions.models import MemberAccount, GiftCoupon
from transactions.views import MemberAccountViewSet
from .serializers import ProfileSerializer, CoachProfileSerializer
import pyuploadcare
import time
import calendar
import csv
from rest_framework.viewsets import ViewSet
from django.http import Http404
from rest_framework.response import Response
from rest_framework.decorators import api_view
from datetime import datetime


class ProfileViewSet(ViewSet):
    def get_or_create(self, request):
        try:
            profile = Profile.objects.get(user=request.user)
        except Profile.DoesNotExist:
            profile = Profile.objects.create(user=request.user)
        return profile

    def list(self, request):
        profile = self.get_or_create(request)
        serializer = ProfileSerializer(profile, many=False)
        return Response(serializer.data)


def set_user_session_variables(request, member_account):
    try:
        if 'member_account_status' in request.session:
            del request.session['member_account_status']
        request.session['member_account_status'] = member_account.status
    except Exception as e:
        print(e)
        pass
    return


@login_required
def index(request):
    profile_view_set = ProfileViewSet()
    member_account_view_set = MemberAccountViewSet()
    profile = profile_view_set.get_or_create(request)
    member_account = member_account_view_set.get_or_start_trial(request)
    member_account = member_account_view_set.check_membership_expired(member_account)
    set_user_session_variables(request, member_account)
    try:
        if request.user.date_joined > datetime(2019, 1, 7).astimezone():
            food_logs = 'false'
        else:
            food_logs = 'true'
    except:
        food_logs = 'false'
    return render(request, 'users/index.html', {
        'member_account': member_account,
        'profile': profile,
        'food_logs': food_logs
    })


@login_required
def account(request):
    try:
        member_account_view_set = MemberAccountViewSet()
        member_account = MemberAccount.objects.get(user=request.user)
        member_account = member_account_view_set.check_membership_expired(member_account)
        period_end = member_account.period_end
        if period_end is not None:
            period_end_date = time.strftime("%a, %d %b %Y", time.gmtime(period_end))
            current_time = calendar.timegm(time.gmtime())
            if int(current_time) > int(period_end):
                update_sub = False
            else:
                update_sub = True
        else:
            update_sub = False
            period_end_date = False
        if member_account.trial_end:
            trial_end = time.strftime("%a, %d %b %Y", time.gmtime(int(member_account.trial_end)))
        else:
            trial_end = None
    except MemberAccount.DoesNotExist:
        member_account = None
        update_sub = False
        period_end_date = None
        trial_end = None
    try:
        facebook_login = request.user.social_auth.get(provider='facebook')
    except UserSocialAuth.DoesNotExist:
        facebook_login = None
    can_disconnect = (request.user.social_auth.count() > 1 or request.user.has_usable_password())
    profile_view_set = ProfileViewSet()
    profile = profile_view_set.get_or_create(request)
    return render(request, 'users/account.html', {
        'facebook_login': facebook_login,
        'can_disconnect': can_disconnect,
        'member_account': member_account,
        'period_end': period_end_date,
        'update_sub': update_sub,
        'profile': profile,
        'profile_pic': profile_pic,
        'trial_end': trial_end,
        'gift_coupons': GiftCoupon.objects.filter(purchased_by=request.user)
    })


@login_required
def membership_options(request):
    try:
        member_account = MemberAccount.objects.get(user=request.user)
    except Exception as e:
        member_account = None
    return render(request, 'users/membership_options.html', {
        'member_account': member_account
    })


@login_required
def payment_success(request):
    try:
        member_account = MemberAccount.objects.get(user=request.user)
    except Exception as e:
        member_account = None
    return render(request, 'users/payment_success.html', {
        'member_account': member_account
    })


@login_required
def gift_coupon(request):
    try:
        member_account = MemberAccount.objects.get(user=request.user)
    except Exception as e:
        member_account = None
    return render(request, 'users/gift_coupon.html', {
        'member_account': member_account
    })


@login_required
def one_time_offers(request):
    try:
        member_account = MemberAccount.objects.get(user=request.user)
    except Exception as e:
        member_account = None
    return render(request, 'users/special_offer.html', {
        'member_account': member_account
    })


@login_required
def profile_pic(request):
    if request.method == 'POST':
        try:
            file = pyuploadcare.File(request.POST.get('my_file'))
            Profile.objects.filter(user=request.user).update(image=file)
            messages.success(request, 'Profile picture uploaded.')
            return redirect('users:account')
        except Exception as e:
            messages.error(request,
                           'Please choose an image and then wait for it to upload before clicking the upload button.')
            return redirect('users:account')

    elif request.method == 'GET':
        profile = Profile.objects.get(user=request.user)
        serializer = ProfileSerializer(profile, many=False)
        return JsonResponse(serializer.data, safe=False)


@login_required
def save_fb_picture(request):
    if request.method == 'POST':
        file = pyuploadcare.File(request.POST.get('file'))
        Profile.objects.filter(user=request.user).update(image=file)
        return HttpResponse(status=200)


@login_required
def update_user_details(request):
    if request.method == "POST":
        User.objects.filter(pk=request.user.id).update(
            first_name=strip_tags(request.POST.get('first_name')),
            last_name=strip_tags(request.POST.get('last_name'))
        )
        messages.success(request, 'Your account details have been updated.')
        return redirect('users:account')


@login_required
def set_first_name(request):
    if request.method == "POST":
        User.objects.filter(pk=request.user.id).update(
            first_name=strip_tags(request.POST.get('first_name'))
        )
        return HttpResponse(status=200)


@login_required
def social_settings_password(request):
    if request.user.has_usable_password():
        PasswordForm = PasswordChangeForm
    else:
        PasswordForm = AdminPasswordChangeForm
    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid() and request.user.email:
            user_account = form.save()
            user_account.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('users:account')
        elif form.is_valid() and strip_tags(request.POST.get('email')):
            email = strip_tags(request.POST.get('email'))
            try:
                user_account = User.objects.get(email__iexact=email)
                form = PasswordForm(request.user)

                return render(request, 'registration/social_settings_password.html', {
                    'form': form,
                    'errors': 'Email is already registered with an account'
                })

            except User.DoesNotExist:
                user_account = form.save()
                user_account.email = email
                user_account.save()
                update_session_auth_hash(request, form.user)
                messages.success(request, 'Your password was successfully updated!')
                return redirect('users:account')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordForm(request.user)
    return render(request, 'registration/social_settings_password.html', {
        'form': form
    })


@login_required
@user_passes_test(lambda u: u.is_superuser)
def export_users_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="users.csv"'
    writer = csv.writer(response)
    writer.writerow(['Email address'])
    users = User.objects.all().values_list('email')
    for user in users:
        writer.writerow(user)
    return response


@login_required
@user_passes_test(lambda u: u.is_superuser)
def export_users_canceled(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="users.csv"'
    writer = csv.writer(response)
    writer.writerow(['email'])
    users = User.objects.filter(memberaccount__status='canceled').order_by('date_joined').values_list('email',
                                                                                                      'date_joined')[
            :10000]
    for user in users:
        writer.writerow(user)
    return response


@login_required
@user_passes_test(lambda u: u.is_superuser)
def export_users_last_challenge(request):

users/templates/users/gift_coupon.html
{% extends 'base.html' %}

{% block pagetitle %} <title>JSA | Gift Coupon</title> {% endblock pagetitle %}

{% block content %}
    <nav class="navbar navbar-expand-sm navbar-light">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="https://d3qqgqjfawam42.cloudfront.net/JSA64x64-purple.svg"/>
            </a>
            <button style="outline:none;" id="navMenu" class="navbar-toggler navbar-toggler-right" type="button"
                    data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03"
                    aria-expanded="false" aria-label="Toggle navigation">
                <i class="fal fa-lg dark-purp fa-bars"></i>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/users/#/">
                            {% if member_account.status == 'active' or member_account.status == 'trialing' %}
                                {% if member_account.membership_name == 'JSA Core' %}
                                    Videos
                                {% else %}
                                    Home
                                {% endif %}
                            {% else %}
                                Home
                            {% endif %}
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:account' %}">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:membership_options' %}">Pricing</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="site-headings">
        <div class="container">
            <div class="row">
                <div class="col d-flex flex-column justify-content-center">
                    <h4>Gift the JSA</h4>
                </div>
            </div>
        </div>
    </div>

    <div class="membership-wrapper grey-background">

        <div class="container" id="membership-container">

            <div class="row">

                <div class="col-lg-6">
                    <div class="content-container text-center shadow-lg">
                        <h5 style="font-weight: 900;">Purchase Gift</h5>
                        <div class="price-circle-black d-flex flex-column justify-content-center">
                            <h4 class="dark-purp m-0" id="amount-3-monthly"></h4>
                            <small>3 Month Block</small>
                        </div>

                        <div class="row">
                            <!-- begin COL -->
                            <div class="col-12">
                                <button id="three-month-button" class="btn index-button btn-block"><i
                                        class="fas fa-credit-card"></i> &nbsp;

                                    Buy Now

                                </button>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="col-lg-6">

                    <div style="margin-top:30px;">

                        <div class="alert alert-primary">
                            <p class="m-0 p-0" id="instructions">
                                Please start by completing the payment. After payment, we will provide you with a
                                coupon, which can be sent to the recipient. All your coupons can be found in your
                                account area.
                            </p>
                        </div>

                        {% if messages %}
                            {% for message in messages %} {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                                <div class="alert alert-danger alert-dismissable">
                                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                    {{ message }}
                                </div>
                            {% endif %} {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}

                                <div class="alert alert-success alert-dismissable">
                                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                    {{ message }}
                                </div>
                            {% endif %} {% endfor %} {% endif %}

                        <form method="POST" action="/transactions/email-gift-coupon/">
                            {% csrf_token %}
                            <input type="hidden" name="couponId" id="couponId">
                            <div class="form-group">
                                <label for="couponValue">Coupon</label>
                                <input type="text" class="form-control" disabled="true" readonly="true"
                                       name="couponValue" id="couponValue" placeholder="Your coupon will show here">
                            </div>
                            <div class="form-group">
                                <label for="recipientEmail">Recipient email</label>
                                <input type="email" class="form-control" disabled="true" name="recipientEmail"
                                       id="recipientEmail" placeholder="Recipient email" required>
                            </div>
                            <div class="form-group">
                                <label for="recipientMessage">Brief message (100 character limit)</label>
                                <textarea maxlength="100" name="recipientMessage" id="recipientMessage" disabled="true"
                                          class="form-control"
                                          placeholder="Happy birthday Diren! Thought you could use this. - Love James"
                                          required></textarea>
                            </div>
                            <button style="display:none;" type="submit" id="sendButton" class="btn btn-primary">Send
                                &nbsp; <i class="fab fa-telegram-plane"></i></button>
                        </form>
                    </div>

                </div>

            </div>

        </div>

    </div>

    {% include "main/relative_footer.html" %}

{% endblock content %}


{% block js_two %}

    <script>
        if (window.innerWidth <= 599) {
            $("#membership-container").removeClass("container");
            $("#membership-container").addClass("container-fluid")
        }
    </script>

    <script src="https://checkout.stripe.com/checkout.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>

    <script src="https://www.paypalobjects.com/api/checkout.js"></script>

    <script>

        //Stripe Script
        $(document).ready(function () {
            $.getJSON("https://api.ipstack.com/check?access_key=189681db139c24dc2fae1557037da6f6", function (e) {
                var t = e.country_name;
                e.ip;
                sessionStorage.removeItem("currency");
                if (t === 'Australia') {
                    sessionStorage.setItem("currency", "aud");
                    $("#amount-3-monthly").html("$148 AUD");
                } else if (t === 'United Kingdom') {
                    sessionStorage.setItem("currency", "gbp");
                    $("#amount-3-monthly").html("£81");
                } else {
                    sessionStorage.setItem("currency", "usd");
                    $("#amount-3-monthly").html("$113 USD");
                }
            }).done(function () {
                console.log("loaded")
            }).fail(function () {
                sessionStorage.removeItem("currency");
                sessionStorage.setItem("currency", "usd");
                $("#amount-3-monthly").html("$113 USD");
            })
        });
        var handler = StripeCheckout.configure({
            key: "pk_live_qN6ztNNx4D0fifPjwxQwufoV",
            image: "https://d3qqgqjfawam42.cloudfront.net/icon.png",
            locale: "auto",
            token: function (e) {
                $('html, body').animate({
                    scrollTop: $("p#instructions").offset().top
                }, 1000);
                $('#instructions').text('Please wait, processing payment...');
                $.ajax({
                    type: "POST",
                    url: "/transactions/stripe-block-purchase/",
                    data: {
                        token: e,
                        tokenId: e.id,
                        tokenEmail: e.email,
                        amount: sessionStorage.amount,
                        months: sessionStorage.months,
                        gift: true,
                        currency: sessionStorage.currency,
                        membership: sessionStorage.membership,
                        csrfmiddlewaretoken: "{{ csrf_token }}"
                    }
                }).done(function (request) {
                    if (request.giftCouponId) {
                        $("#sendButton").show();
                        document.getElementById("couponId").value = request.giftCouponId;
                        document.getElementById("couponValue").value = request.coupon;
                        document.getElementById("recipientEmail").disabled = false;
                        document.getElementById("couponValue").disabled = false;
                        document.getElementById("recipientMessage").disabled = false;
                        $('#instructions').text('Your payment was successful! Please now complete the form below if you would like to email the recipient the gift coupon. If you do not want to, you can access the gift coupon in your account area to give to the recipient later.');
                    } else {
                        alert('There has been an error! Please contact us.');
                    }
                }).fail(function (e) {
                    alert('There has been an error! Please contact us.');
                })
            }
        });
        document.getElementById("three-month-button").addEventListener("click", function (e) {
            sessionStorage.removeItem("amount"), sessionStorage.removeItem("months"), sessionStorage.removeItem("membership"), sessionStorage.setItem("months", 3), "aud" === sessionStorage.currency ? sessionStorage.setItem("amount", 14800) : "gbp" === sessionStorage.currency ? sessionStorage.setItem("amount", 8100) : "usd" === sessionStorage.currency && sessionStorage.setItem("amount", 11300), sessionStorage.setItem("membership", "Premium Plan - 3 Month Block"), handler.open({
                name: "Premium Plan - 3 Month Block",
                description: "Purchase of a Premium Plan 3 month block from James Smith Academy Pty Ltd (ABN:72621129511)",
                zipCode: !0,
                currency: sessionStorage.currency,
                amount: sessionStorage.amount,
                billingAddress: !0
            }), e.preventDefault()
        });

        window.addEventListener("popstate", function () {
            handler.close()
        });

    </script>

{% endblock js_two %}

users/templates/users/payment_success.html
{% extends 'base.html' %}

{% block pagetitle %} <title>Payment Success</title> {% endblock pagetitle %}

{% block content %}
	<nav class="navbar navbar-expand-sm navbar-light">
		<div class="container">
			<a class="navbar-brand" href="/">
		  		<img src="https://d3qqgqjfawam42.cloudfront.net/JSA64x64-purple.svg" />
			</a>
			<button style="outline:none;" id="navMenu" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
	        	<i class="fal fa-lg dark-purp fa-bars"></i>
	      	</button>

			<div class="collapse navbar-collapse" id="navbarTogglerDemo03">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link" href="/users/#/">
							{% if member_account.status == 'active' or member_account.status == 'trialing' %}
							  {% if member_account.membership_name == 'JSA Core' %}
							  	Videos
							  {% else %}
							  	Home
							  {% endif %}
							{% else %}
							 	Home
							{% endif %}
						</a>
					</li>
				</ul>
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users:account' %}">Account</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{% url 'users:membership_options' %}">Pricing</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="site-headings">
		<div class="container">
			<div class="row">
			  	<div class="col d-flex flex-column justify-content-center">
					<h4>Payment Success</h4>
				</div>
			</div>
		</div>
	</div>

	<div class="membership-wrapper grey-background">

		<div class="container">
				
			<div class="row justify-content-center">
					
				<div class="col-lg-6">
					
					<div class="content-container">
						
						<div class="text-center m-2">
							<i class="fal fa-5x green fa-check-circle"></i>
						</div>

						<div class="text-center m-2 green">
							<p>Payment Successful</p>
						</div>

						<div class="text-center m-2">
                            <h6>Welcome {{ user.username }}</h6>
							<p>We look forward to working with you!</p>
						</div>

						<div class="text-center m-2">
							<p>View your account details and manage your membership on your account page. </p>
						</div>

						<hr/>

						<div class="text-center m-2">
							<a href="/users/account/"><u>Your Account</u></a>
						</div>

					</div>

				</div>

			</div>

		</div>

	</div>
		
	{% include "main/relative_footer.html" %}

{% endblock content %} 


{% block js_two %}

	

{% endblock js_two %}