academy/urls.py
from django.urls import path, include
from django.contrib import admin
from django.views.generic import TemplateView
from rest_framework.documentation import include_docs_urls
from rest_framework import permissions

urlpatterns = [

    path('', TemplateView.as_view(template_name="main/index.html")),
    path('docs/', include_docs_urls(title='JSA API', public=False, permission_classes=(permissions.IsAdminUser,))),
    path('terms/', TemplateView.as_view(template_name="main/terms_of_service.html")),
    path('upgrade-now/', TemplateView.as_view(template_name="main/upgrade_now.html")),
    path('fat-loss-init/', TemplateView.as_view(template_name="main/fat_loss_landing.html")),
    path('transformations/', TemplateView.as_view(template_name="main/transformations.html")),
    path('member-of-the-month/', TemplateView.as_view(template_name="main/member_of_the_month.html")),
    path('privacy/', TemplateView.as_view(template_name="main/privacypolicy.html")),
    path('cookies-policy/', TemplateView.as_view(template_name="main/cookies_policy.html")),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('emails/', include(('emails.urls', 'emails'), namespace='emails')),
    path('transactions/', include(('transactions.urls', 'transactions'), namespace='transactions')),
    path('weeks/', include(('weeks.urls', 'weeks'), namespace='weeks')),
    path('chat/', include(('chat.urls', 'chat'), namespace='chat')),
    path('modules/', include(('modules.urls', 'modules'), namespace='modules')),
    path('progress/', include(('progress.urls', 'progress'), namespace='progress')),
    path('recipes/', include(('recipes.urls', 'recipes'), namespace='recipes')),
    path('training/', include(('training.urls', 'training'), namespace='training')),
    path('accounts/', include('registration.backends.default.urls')),
    path('oauth/', include(('social_django.urls', 'social_django'), namespace='social')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('coaches/', include(('coaches.urls', 'coaches'), namespace='coaches')),
    path('challenge/', include(('challenge.urls', 'challenge'), namespace='challenge')),
    path('analytics/', include(('analytics.urls', 'analytics'), namespace='analytics')),
    path('nutrition-tracker/', include(('nutrition_tracker.urls', 'nutrition'), namespace='nutrition_tracker')),
    path('foods/', include(('foods.urls', 'foods'), namespace='foods')),
    path('home-steps/', include(('home_steps.urls', 'home_steps'), namespace='home_steps')),
    path('jsa-admin-coach-login/', admin.site.urls),

]

blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^view/(?P<slug>[^\.]+).html', views.view_post, name='view_blog_post'),
	url(r'^category/(?P<slug>[^\.]+).html', views.view_category, name='view_blog_category'),
]

users/urls.py
from django.urls import path
from . import views
from .backends import Register
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='home'),
    path('account/', views.account, name='account'),
    path('membership-options/', views.membership_options, name='membership_options'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('gift-coupon/', views.gift_coupon, name='gift_coupon'),
    path('coach-profile/', views.coach_profile, name='coach_profile'),
    path('one-time-offers/', views.one_time_offers, name='one_time_offers'),
    path('profile/picture/', views.profile_pic, name='profile_pic'),
    path('save-fb-picture/', views.save_fb_picture, name='save_fb_picture'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('register/', Register.as_view(), name='user_register'),
    path('social/settings/password', views.social_settings_password, name='social_settings_password'),
    path('update-details/', views.update_user_details, name='update_user_details'),
    path('set-first-name/', views.set_first_name, name='set_first_name'),
    path('csv-export/', views.export_users_csv, name='export_users_csv'),
    path('export-users-canceled/', views.export_users_canceled, name='export_users_canceled'),
    path('export-users-last-challenge/', views.export_users_last_challenge, name='export_users_last_challenge'),
]

main/models.py
from django.db import models

# Create your models here.

main/templates/main/cookies_policy.html
{% extends 'base.html' %}

{% block pagetitle %}<title>JSA | Cookies Policy</title>{% endblock pagetitle %} 

{% load cache %}
{% block content %}
{% include "main/nav.html" %}
{% cache 86400 cookies %}

<div class="privacypolicy-wrapper container">
  <div style="max-width: 700px; margin:auto;">
    <h4 class="text-center">Cookies Policy</h4>
      <section class="privacy-policy-container">
        <h5>About cookies</h5>
        <p>
          Cookies are small text and data files which are downloaded and stored on your computer or a mobile device when you visit a website. James Smith Academy Pty Ltd ACN 621 129 511 (James Smith Academy, us, our, and/or we) uses cookies to assist with the operation of our website and services.
        </p>
        <p>
          Some of the cookies on our website are ‘first party cookies’ which are sent from our website to your browser and allow us to customise our service to you by storing data such as your login details as a convenience to you next time you log in. 
        </p>
        <p>
          The James Smith Academy website also contains ‘third party cookies’ which are text and data files from external businesses that provide content, payment services or advertising on websites that you visit.
        </p>
        <p>
          Cookies which are required to assist with the operation of a website are referred to as strictly necessary or essential cookies. Cookies which do not fall into this category are used for other purposes such as delivery of video content, payment, advertising, social media and tracking of your online movements. 
        </p>
      </section>
      <section class="privacy-policy-container">
        <h5>Why do we use cookies?</h5>
        <p>
          The cookies contained on our website are both first and third party cookies.. The specific types of first and third-party cookies contained on the James Smith Academy website and the purposes for which they are used is disclosed in full below. Before you use the James Smith Academy website for the first time, we will notify you that our website contains cookies and ask you to consent to our use of cookies in our interactions with you. In addition, You may manage your cookie preferences by clicking <a href="javascript: Cookiebot.renew()">here</a>.
        </p>
        <p>
          Alternatively, you may choose to disable some or all cookies by refusing to consent to our use of cookies or blocking the cookies through  your browser. However, please note that if you do disable cookies from accessing your browser,  some of the features of the site will may not work and we may not be able to provide you with the complete James Smith Academy services. 
        </p>
        <p>
          Please note that any Personal Information about you which is collected by us through our use of cookies will be handled in accordance with our Privacy Policy, located at the following URL:  <a href="https://www.jamessmithacademy.com/privacy/">https://www.jamessmithacademy.com/privacy/</a>.
        </p>
      </section>
      <section class="privacy-policy-container">
        <h5>Cookies</h5>

        <section class="cookies-wrapper">
          <h6 class="cookies-type-heading">Essential cookies</h6>
           <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col" style="width: 50%">Category & Purpose</th>
                  <th scope="col" style="width: 50%">Cookies</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>These cookies are required so that we can provide you with the services available on our website. These cookies are primarily used at login and while using the features of the James Smith Academy website.</td>
                  <td>
                    <div class="cookie-used">csrftoken</div>
                    <div class="cookie-used">sessionid</div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <section class="cookies-wrapper">
          <h6 class="cookies-type-heading">Performance and functionality cookies</h6>
          <div class="table-responsive">
            <table class="table" >
              <thead>
                <tr>
                  <th scope="col" style="width: 50%">Category & Purpose</th>
                  <th scope="col" style="width: 50%">Cookies</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    <h6>Vimeo</h6>
                    One of the core features of the James Smith Academy website is the training videos which have been uploaded by our coaches. We use Vimeo to deliver this video content, which contains the following cookies.
                  </td>
                  <td>
                    <div class="cookie-used">vuid</div>
                  </td>
                </tr>
                <tr>
                  <td>
                    <h6>Stripe</h6>
                    James Smith Academy uses Stripe is one of its payment providers when customers make payments via our website. Stripe contains the following cookies. 
                  </td>
                  <td>
                    <div class="cookie-used">__stripe_mid</div>
                    <div class="cookie-used">user</div>
                    <div class="cookie-used">stripe.csrf</div>
                    <div class="cookie-used">session</div>
                    <div class="cookie-used">private_machine_identifier</div>
                    <div class="cookie-used">logged_in</div>
                    <div class="cookie-used">lang</div>
                    <div class="cookie-used">country</div>
                    <div class="cookie-used">cid</div>
                    <div class="cookie-used">checkout-test-session</div>
                    <div class="cookie-used">checkout-live-session</div>
                    <div class="cookie-used">__stripe_sid</div>
                    <div class="cookie-used">__stripe_orig_props</div>
                    <div class="cookie-used">__stripe_mid</div>
                  </td>
                </tr>
                <tr>
                  <td>
                    <h6>PayPal</h6>
                    James Smith Academy also uses PayPal as one of its payment providers. PayPal contains the following cookies. 
                  </td>
                  <td>
                    <div class="cookie-used">X-PP-SILOVER</div>
                    <div class="cookie-used">x-csrf-jwt</div>
                    <div class="cookie-used">tsrce</div>
                    <div class="cookie-used">ts</div>
                    <div class="cookie-used">nsid</div>
                    <div class="cookie-used">LANG</div>
                    <div class="cookie-used">AKDC</div>
                    <div class="cookie-used">akavpau_ppsd</div>
                    <div class="cookie-used">_cookiecheck</div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <section class="cookies-wrapper">
          <h6 class="cookies-type-heading">Analytics cookies</h6>
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col" style="width: 50%">Category & Purpose</th>
                  <th scope="col" style="width: 50%">Cookies</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    <h6>Google Analytics</h6>
                    We use Google Analytics  to monitor the number of users on our website and their movement through the different pages. 
                  </td>
                  <td>
                    <div class="cookie-used">_gid</div>
                    <div class="cookie-used">_ga</div>
                  </td>
                </tr>
                <tr>
                  <td>
                    <h6>Facebook Pixel</h6>
                    We use Facebook Pixel to monitor how many views our website receives as a result of Facebook and our Facebook adverts.
                  </td>
                  <td>
                    <div class="cookie-used">xs</div>
                    <div class="cookie-used">wd</div>
                    <div class="cookie-used">sb</div>
                    <div class="cookie-used">presence</div>
                    <div class="cookie-used">pl</div>
                    <div class="cookie-used">m_pixel_ratio</div>
                    <div class="cookie-used">locale</div>
                    <div class="cookie-used">fr</div>
                    <div class="cookie-used">dpr</div>
                    <div class="cookie-used">datr</div>
                    <div class="cookie-used">c_user</div>
                    <div class="cookie-used">act</div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <section class="cookies-wrapper">
          <h6 class="cookies-type-heading">Advertising cookies</h6>
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col" style="width: 50%">Category & Purpose</th>
                  <th scope="col" style="width: 50%">Cookies</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    <h6>Facebook Ads</h6>
                    Facebook Adverts is used so that we can acquire new customers. 
                  </td>
                  <td>
                    <div class="cookie-used">xs</div>
                    <div class="cookie-used">wd</div>
                    <div class="cookie-used">sb</div>
                    <div class="cookie-used">presence</div>
                    <div class="cookie-used">pl</div>
                    <div class="cookie-used">m_pixel_ratio</div>
                    <div class="cookie-used">locale</div>
                    <div class="cookie-used">fr</div>
                    <div class="cookie-used">dpr</div>
                    <div class="cookie-used">datr</div>
                    <div class="cookie-used">c_user</div>
                    <div class="cookie-used">act</div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>
      </section>
      <section class="privacy-policy-container">
        <h5>Contacting us about Cookies</h5>
        <p>
          If you have a complaint about our use of cookies, or have another query about the information contained in this policy, you may contact us at contact@jamessmithacademy.com or by otherwise sending your query or complaint to: 
        </p>
        <p>
          The Privacy Officer <br>
          James Smith Academy Holdings Pty Ltd <br>
          121 Beattie Street <br>
          Balmain, Sydney NSW 2041 <br>
        </p>
      </section>
      <section class="privacy-policy-container">
        <h5>Updates to this policy</h5>
        <p>
          This cookies policy is subject to change without prior or separate notification. Any changes will be posted on our website.
        </p>
        <p>
          This cookies policy was last updated on 25 May 2018. 
        </p>
      </section>
  </div>
</div>

{% endcache %}
{% include "main/relative_footer.html" %}
{% endblock content %}

main/templates/main/footer.html
<footer>
  <div class="container">
    <div class="row footer">
      <div class="col-lg col-md">
        <div class="fb-like" data-href="https://www.facebook.com/JamesSmithPT/" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="true"></div>
      </div>
      <div class="col-lg col-md">
        <a class="align-middle" href="/emails/contact-us">
          Contact Us
        </a>
      </div>
      <div class="col-lg col-md">
          <a class="align-middle" href="/terms">Terms of Service</a>
      </div>
      <div class="col-lg col-md">
        <a class="align-middle"  href="/privacy">Privacy Policy</a>
      </div>
      <div class="col-lg col-md">
        <p class="align-middle">&copy; {% now "Y" %} James Smith Academy Pty Ltd</p>
      </div>
    </div>
  </div>
</footer>

main/templates/main/nav.html
<nav class="navbar navbar-expand-md navbar-light">
	<div class="container">
		<a class="navbar-brand" href="/" hreflang="en-us">
			<img src="https://d3qqgqjfawam42.cloudfront.net/JSA64x64-purple.svg" alt="The Academy">
		</a>
		<button style="outline:none;" id="navMenu" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fal fa-lg fa-bars dark-purp"></i>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/emails/daily-email/" hreflang="en-us">Daily Email</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/transformations/" hreflang="en-us">Transformations</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:index' %}" hreflang="en-us">
              Blog
            </a>
          </li>
        </ul>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a  class="nav-link" href="{% url 'users:home' %}" hreflang="en-us">{{user.username}} &nbsp; <i class="far fa-sign-in"></i></a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}" hreflang="en-us"><strong>Login</strong></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/users/register/"><strong>Join Now</strong></a>
              </li>
            {% endif %}
        </ul>
      </div>
	</div>
</nav>

main/templates/main/nav_fixed.html
<nav class="navbar navbar-fixed navbar-expand-md navbar-dark">
  <div class="container">
    
      <a class="navbar-brand" href="/" hreflang="en-us">
        <img src="https://d3qqgqjfawam42.cloudfront.net/JSA64x64-white.svg" alt="The Academy">
      </a>

      <button style="outline:none;" id="navMenu" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fal fa-lg fa-bars white"></i>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/emails/daily-email/" hreflang="en-us">Daily Email</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/transformations/" hreflang="en-us">Transformations</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:index' %}" hreflang="en-us">
              Blog
            </a>
          </li>
        </ul>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a  class="nav-link" href="{% url 'users:home' %}" hreflang="en-us">{{user.username}} &nbsp; <i class="far fa-sign-in"></i></a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}" hreflang="en-us"><strong>Login</strong></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/users/register/"><strong>Join Now</strong></a>
              </li>
            {% endif %}
        </ul>
      </div>

  </div>
</nav>

main/templates/main/relative_footer.html
<footer>
  <div class="container" style="max-width: 700px;">
    <div class="relative-footer">
      <div class="row">
      <div class="col-lg col-md">
        <a  href="/terms">Terms of Service</a>
      </div>
      <div class="col-lg col-md">
        <a  href="/privacy">Privacy Policy</a>
      </div>
      <div class="col-lg col-md">
        <a  href="/cookies-policy">Cookies Policy</a>
      </div>
      <div class="col-lg col-md">
        <a href="/emails/contact-us">
             Contact Us
        </a>
      </div>
      <div class="col-lg col-md">
          <div class="fb-like" data-href="https://www.facebook.com/JamesSmithPT/" data-colorscheme="dark" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="false"></div>
      </div>
    </div>
    </div>
  </div>
  <div class="lower-footer">
    <div class="container">
      <div class="row">
        <div class="col text-center">
          &copy; {% now "Y" %} James Smith Academy Pty Ltd &nbsp; | &nbsp; All Rights Reserved
        </div>
      </div>
    </div>
  </div>
</footer>